Repository codethechange/culturemeshFFB, pull requests merged in 2018-12, with the labels that each got.

#84 Upgrade Requests package to 2.20.1
  requirements.txt
Labels: security

#82 Add `/dev/note` endpoint for live testing
  culturemesh/__init__.py
  culturemesh/blueprints/dev/__init__.py
  culturemesh/blueprints/dev/controllers.py
  culturemesh/blueprints/dev/templates/note.html
  docs/source/testing.rst
Labels: enhancement

#86 Index page ui
  .gitignore
  culturemesh/client/posts.py
  culturemesh/static/css/culturemesh-style.css
  culturemesh/templates/index.html
Labels: enhancement

#99 Set Defaults for about_me and gender
  culturemesh/views.py
Labels: bug
